version: "3"

services:
  bot:
    build:
      context: "."
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME}
      - GOOGLESHEET_KEY_FILE=${GOOGLESHEET_KEY_FILE}
      - GOOGLESHEET_URL=${GOOGLESHEET_URL}
    volumes:
      - "./:/codebase"
    restart: always
